# daily prtdb to monthly prtdb
final_prtdb <- function(year, month, day) {
  
  # Load necessary libraries
  library(dplyr)
  library(lubridate)
  
  # Load the dataframe
  load("df_adjusted.RData")
  View(df_adjusted)
  # Construct the date string and filter the dataframe
  target_date <- as.Date(paste(year, month, day, sep = "-"))
  df_modified <- df_adjusted %>%
    filter(date <= target_date)
  
  # Find the end of the current quarter
  end_of_quarter <- ceiling_date(target_date, "quarter") - days(1)
  extended_dates <- seq.Date(from = target_date + days(1), to = end_of_quarter, by = "day")
  
  # Define the release dates for each series
  delays <- list(
    pib = c(1, 90),
    expec = c(1, 7),
    pim = c(4, 52),
    pim_bk = c(4, 52),
    pim_bi = c(4, 52),
    pmca = c(14, 52),
    area = c(13, 48),
    housing = c(12, 48),
    pmcv = c(14, 52),
    pmc_comb = c(14, 52),
    pmc_super = c(14, 52),
    tecidos = c(14, 52),
    nuci = c(2, 28),
    ibc_br = c(26, 56),
    caged_a12 = c(26, 54),
    ABPO = c(3, 28),
    fenabrave = c(25, 28),
    anp = c(16, 28),
    ibov = c(6, 87),
    anfavea = c(6, 31),
    bp = c(4, 28),
    idp = c(4, 28),
    expinf = c(5, 27),
    primario = c(28, 27),
    credito = c(26, 27),
    ettj = c(19, 27),
    cambio = c(5, 25),
    cdi = c(19, 54),
    m2 = c(4, 52),
    imports = c(4, 28),
    Energia = c(8, 145),
    icea = c(6, 63),
    iec = c(6, 62),
    exports = c(9, 28),
    iof = c(17, 32),
    nasdaq = c(4, 22),
    dow_jones = c(4, 22)
  )
  
  # Create a dataframe with the extended dates
  extended_df <- data.frame(date = extended_dates)
  
  for (series_name in names(df_modified)[-1]) {
    if (series_name %in% names(delays)) {
      delay_info <- delays[[series_name]]
      release_day <- delay_info[1]
      delay_days <- delay_info[2]
      
      # Calculate the release date for the last month in the dataframe
      last_month <- floor_date(target_date, unit = "month")
      last_release_date <- last_month + days(release_day - 1)
      
      # Determine if the input date is before or after the release date
      if (target_date < last_release_date) {
        # Fill with NA from the start of the month until the end of the quarter
        series_data <- df_modified %>%
          filter(date < last_month) %>%
          slice_tail(n = 1) %>%
          pull(!!sym(series_name))
        
        extended_series <- c(rep(NA, length(extended_dates)))
        
        # Insert NA from the start of the month
        df_modified[df_modified$date >= last_month, series_name] <- NA
        extended_df[[series_name]] <- extended_series
      } else {
        # Repeat the last available value until the end of the current month
        series_data <- df_modified %>%
          filter(!is.na(!!sym(series_name))) %>%
          slice_tail(n = 1) %>%
          pull(!!sym(series_name))
        
        extended_series <- if (month(target_date) == month(end_of_quarter)) {
          rep(series_data, length(extended_dates))
        } else {
          # Repeat the value only for the days in the current month
          next_month_start <- ceiling_date(target_date, "month")
          days_in_current_month <- seq.Date(from = target_date + days(1), to = next_month_start - days(1), by = "day")
          c(rep(series_data, length(days_in_current_month)), rep(NA, length(extended_dates) - length(days_in_current_month)))
        }
        
        extended_df[[series_name]] <- extended_series
      }
    } else {
      extended_df[[series_name]] <- NA
    }
  }
  
  # Bind the extended dataframe to the filtered dataframe
  df_extended <- bind_rows(df_modified, extended_df)
  
  return(df_extended)
}
daily_to_monthly <- function(daily_df) {
  monthly_df <- daily_df %>%
    mutate(month = floor_date(date, "month")) %>%
    group_by(month) %>%
    summarise(across(where(is.numeric), ~ ifelse(all(is.na(.)), NA, last(na.omit(.))))) %>%
    ungroup() %>%
    rename(date = month)
  
  return(monthly_df)
}

# Example usage with the dataframe generated by final_prtdb
daily <- final_prtdb(2023, 10, 03)
monthly <- daily_to_monthly(daily)
# adjusting discrepancies
monthly[nrow(monthly),2] <- NA
monthly[nrow(monthly)-1,2] <- NA
monthly[nrow(monthly)-2,2] <- NA
